version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/npm/cypress-screenplay"
    versioning-strategy: increase
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/npm/@silverback/prettier-config"
    versioning-strategy: increase
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/npm/@silverback/eslint-config"
    versioning-strategy: increase
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/npm/@silverback/eslint-config-react"
    versioning-strategy: increase
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/npm/verdaccio-git"
    versioning-strategy: increase
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/packages/composer/amazeelabs/silverback-cli"
    versioning-strategy: increase
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/apps/silverback-drupal"
    versioning-strategy: increase
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/packages/composer/drupal/cypress"
    versioning-strategy: increase
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/composer/drupal/cypress"
    versioning-strategy: increase
    schedule:
      interval: "daily"
