silverback_gutenberg.settings:
  type: config_object
  label: 'Silverback Gutenberg settings'
  mapping:
    local_hosts:
      type: sequence
      nullable: true
      label: 'URLs with these hosts will be turned to relative. If null, any absolute URLs will NOT be processed (BC behavior).'
      sequence:
        type: string
        label: 'Host'
