name: 'Commons'
description: 'Commons for all workflows'
runs:
  using: 'composite'
  steps:
    - name: Git mail
      run: git config --global user.email "kitt@amazee.com"
      shell: bash

    - name: Git username
      run: git config --global user.name "K.I.T.T."
      shell: bash

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.9.0
      with:
        enable-cache: 'true'
    - name: Load devbox via direnv
      uses: HatsuneMiku3939/direnv-action@v1

    - name: Check xdebug config
      shell: bash
      run: |
        if ! php --info | grep 'xdebug.mode => develop => develop'; then
          echo 'Error: xdebug.mode should not be set in CI. Have you committed xdebug config by accident? Check devbox.d/php/php.ini'
          exit 1
        fi

    - name: Tell pnpm to use Bash
      run: pnpm config set script-shell /bin/bash
      shell: bash

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: /tmp/cache
        key: |
          cache-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          cache-${{ hashFiles('**/pnpm-lock.yaml') }}-
          cache-
    - name: Set composer cache dir
      run: composer config --global cache-files-dir /tmp/cache/composer
      shell: bash
    - name: Set pnpm cache dir
      run: pnpm config set store-dir /tmp/cache/pnpm
      shell: bash
    - name: Set Playwright browsers dir
      run:
        echo "PLAYWRIGHT_BROWSERS_PATH=/tmp/cache/playwright-browsers" >>
        $GITHUB_ENV
      shell: bash
    - name: Set Cypress cache dir
      run: echo "CYPRESS_CACHE_FOLDER=/tmp/cache/cypress-binary" >> $GITHUB_ENV
      shell: bash
