language: php
dist: xenial
sudo: false

php:
  # This PHP version (which is set by Travis via phpenv) is overridden in the
  # before_install section.
  - '7.3'

cache:
  directories:
    - ~/.npm
    - ~/.cache
    - ~/.composer/cache

addons:
  apt:
    sources:
      # Third party apt-repositories are removed from Xenial Build Environment:
      # https://docs.travis-ci.com/user/reference/xenial/
      # We need to add PHP repository ourselves.
      - sourceline: 'ppa:ondrej/php'
    packages:
      - libgconf-2-4
      # Install PHP and extensions.
      - php7.3
      - php7.3-common
      - php7.3-xml
      - php7.3-xmlrpc
      - php7.3-curl
      - php7.3-imap
      - php7.3-mbstring
      - php7.3-opcache
      - php7.3-soap
      - php7.3-json
      - php7.3-zip
      - php7.3-intl
      - php7.3-sqlite
      - php7.3-gd
      - php7.3-imagick

before_install:
  # Override the phpenv's PHP to the one we installed via APT. We do this to
  # workaround the "too many SQL variables" error which happens when SQLite's
  # SQLITE_MAX_VARIABLE_NUMBER parameter is set to the default value (999).
  - sudo cp /usr/bin/php7.3 `which php`
  - php --version
  - echo 'sendmail_path = /bin/true' | sudo tee -a `php -r 'echo php_ini_loaded_file();'`
  - composer self-update
  # Use node version set in .nvmrc file.
  - nvm install && nvm use

install:
  - composer install
  - yarn install
  - source .envrc

script:
  - silverback setup
  - drush serve :8889 > log.txt 2>&1 &
  # Wait for drush serve to start up, but only for 20 seconds.
  - |
    DRUSH_SERVE_WAIT=0; \
    until curl -sS http://127.0.0.1:8889 >/dev/null || (($DRUSH_SERVE_WAIT > 19)); \
    do sleep 1 && \
      DRUSH_SERVE_WAIT=$(($DRUSH_SERVE_WAIT + 1)) && \
      echo "Waited $DRUSH_SERVE_WAIT seconds for drush serve."; \
    done
  - composer run-script run-tests --timeout 0

notifications:
  email: false

