<?php

use Drupal\Core\Asset\AttachedAssetsInterface;

/**
 * Implements hook_js_settings_alter().
 */
function gutenberg_custom_js_settings_alter(array &$settings, AttachedAssetsInterface $assets) {
  if (isset($settings['gutenberg']['theme-support'])) {
    $settings['gutenberg']['theme-support'] = [

        // Disable text colors.
        'colors' => [],
        'disableCustomColors' => TRUE,

        // Disable font sizes.
        'fontSizes' => [],
        'disableCustomFontSizes' => TRUE,

      ] + $settings['gutenberg']['theme-support'];
  }
}

/**
 * Implements hook_library_info_alter().
 */
function gutenberg_custom_library_info_alter(&$libraries, $extension) {
  if ($extension === 'gutenberg') {
    $libraries['edit-node']['dependencies'][] = 'gutenberg_custom/tweaks';
  }
}
