silverback_cloudinary.cloudinary.*:
  type: config_entity
  label: 'Cloudinary instance config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    cloud_name:
      type: string
      label: 'Cloud name'
    api_key:
      type: string
      label: 'API Key'
    api_secret:
      type: string
      label: 'API Secret'
