[dev]
autoLaunch = false

[build]
base = "packages/npm/@amazeelabs/token-auth-middleware"
edge_functions = "netlify/edge-functions"
publish = "site"

[[edge_functions]]
path = "/restricted/*"
function = "token-auth"
