<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Markup;
use Drupal\Core\Url;
use Drupal\silverback_gatsby\Gatsby;

/**
 * Implements hook_entity_insert().
 */
function silverback_gatsby_entity_insert(EntityInterface $entity) {
  Gatsby::onEntityOperation($entity);
}

/**
 * Implements hook_entity_update().
 */
function silverback_gatsby_entity_update(EntityInterface $entity) {
  Gatsby::onEntityOperation($entity);
}

/**
 * Implements hook_entity_delete().
 */
function silverback_gatsby_entity_delete(EntityInterface $entity) {
  Gatsby::onEntityOperation($entity);
}

/**
 * Implements hook_toolbar().
 */
function silverback_gatsby_toolbar() {
  return [
    'silverback_gatsby_preview_refresh_status' => [
      '#type' => 'toolbar_item',
      'tab' => [
        '#type' => 'link',
        '#title' => 'Gatsby Preview status: Idle',
        '#url' => Url::fromUri(Gatsby::PREVIEW_URL),
        '#attributes' => [
          'class' => ['silverback-gatsby-preview-refresh-status-link'],
        ],
      ],
      '#attached' => [
        'library' => ['silverback_gatsby/refresh_status'],
        'drupalSettings' => [
          'isGatsbyRefreshingUrl' => Gatsby::IS_REFRESHING_PREVIEW_URL,
        ],
      ],
      '#weight' => 1000,
    ],
  ];
}
