<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\silverback_gatsby\Gatsby;

/**
 * Implements hook_entity_insert().
 */
function silverback_gatsby_entity_insert(EntityInterface $entity) {
  Gatsby::onEntityOperation($entity);
}

/**
 * Implements hook_entity_update().
 */
function silverback_gatsby_entity_update(EntityInterface $entity) {
  Gatsby::onEntityOperation($entity);
}

/**
 * Implements hook_entity_delete().
 */
function silverback_gatsby_entity_delete(EntityInterface $entity) {
  Gatsby::onEntityOperation($entity);
}
