docker-compose-yaml: docker-compose.yml

project: ${COMPOSE_PROJECT_NAME}

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    - run:
        name: IF no Drupal install via drush si
        command: |
            if ! drush status --fields=bootstrap | grep -q "Successful"; then
                # no drupal installed, we install drupal from scratch
                drush si -y minimal --sites-subdir=default --existing-config --account-name=admin --account-pass=admin
            fi
        service: cli
        shell: bash
    - run:
        name: drush updb
        # Sometimes a cache clear is required prior to running database updates.
        # For example, see https://www.drupal.org/project/drupal/issues/2952071
        # Make two database update attempts to workaround this issue.
        command: drush -y updb --entity-updates --cache-clear=0 || (drush cr && drush -y updb --entity-updates --cache-clear=0)
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush webpack:build
        command: if drush | grep -q "webpack:build"; then drush webpack:build; fi
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli
#    - run:
#        name: Fast-forward tracking branches
#        # During a deploy to prod, create a new local branch from the origin's
#        # prod branch, then push that new branch to origin. Since the new local
#        # branch name matches an existing branch name on origin, a fast-forward
#        # merge will occur.
#        command: |
#            if [[ ${LAGOON_GIT_SAFE_BRANCH} == "prod" ]]; then
#              git fetch origin prod:demo && git push origin demo || echo "Fast-forward of \"demo\" branch failed."
#            fi
#        service: cli
#        shell: bash



environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
    routes:
        - varnish:
            - "${AMAZEEIO_PROJECT_URL}"
