query FeedInfo($lastBuild: Int, $currentBuild: Int) {
  drupalBuildId
  drupalFeedInfo {
    typeName
    singleFieldName
    listFieldName
    changes(lastBuild: $lastBuild, currentBuild: $currentBuild)
  }
}
