FROM amazeeio/php:7.2-cli-drupal

COPY composer.json composer.lock load.environment.php /app/
COPY scripts /app/scripts
RUN composer install --no-dev
COPY . /app

# Define where the Drupal Root is located
ENV WEBROOT=web
ENV SB_ENVIRONMENT=amazeeio
