language: php
dist: xenial
sudo: false

php:
  # This PHP version (which is set by Travis via phpenv) is overridden in the
  # before_install section.
  - '7.4'

addons:
  apt:
    sources:
      # Third party apt-repositories are removed from Xenial Build Environment:
      # https://docs.travis-ci.com/user/reference/xenial/
      # We need to add PHP repository ourselves.
      - sourceline: 'ppa:ondrej/php'
    packages:
      - libgconf-2-4
      # Install PHP and extensions.
      - php7.4
      - php7.4-common
      - php7.4-xml
      - php7.4-xmlrpc
      - php7.4-curl
      - php7.4-imap
      - php7.4-mbstring
      - php7.4-opcache
      - php7.4-soap
      - php7.4-json
      - php7.4-zip
      - php7.4-intl
      - php7.4-sqlite
      - php7.4-gd
      - php7.4-imagick

env:
  global:
  - DRUPAL_BUILD_DIR=$TRAVIS_BUILD_DIR/../drupal
  - COMPOSER_MEMORY_LIMIT=-1

cache:
  directories:
  - node_modules
  - ~/.npm
  - ~/.cache
  - ~/.composer/cache

before_install:
  # Override the phpenv's PHP to the one we installed via APT. We do this to
  # workaround the "too many SQL variables" error which happens when SQLite's
  # SQLITE_MAX_VARIABLE_NUMBER parameter is set to the default value (999).
  - sudo cp /usr/bin/php7.4 `which php`
  - php --version
  - echo 'sendmail_path = /bin/true' | sudo tee -a `php -r 'echo php_ini_loaded_file();'`
  - composer self-update
    # Use node version set in .nvmrc file.
  - nvm install && nvm use

install:
- composer create-project drupal/recommended-project $DRUPAL_BUILD_DIR --no-interaction
- cd $DRUPAL_BUILD_DIR
- composer remove drupal/core
- php -r "\$json = json_decode(file_get_contents('composer.json'), TRUE); \$json['repositories'][] = ['type' => 'path', 'url' => '$TRAVIS_BUILD_DIR' ]; \$json['repositories'][] = ['type' => 'vcs', 'url' => 'git@github.com:AmazeeLabs/cypress.git' ]; file_put_contents('composer.json', json_encode(\$json, JSON_PRETTY_PRINT));"
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo $BRANCH
- COMPOSER_MEMORY_LIMIT=-1 composer require "amazeelabs/silverback:dev-$BRANCH"
- ./vendor/bin/silverback init
- composer install
- source .envrc
- yarn

script:
- silverback download-tests
- cp cypress/integration/jira/SLB/* vendor/amazeelabs/silverback/cypress/integration
- vendor/bin/silverback setup && vendor/bin/drush en cypress -y
- vendor/bin/drush cypress:list
- silverback-test silverback
- kill $(jobs -p) || true

notifications:
  email: false

