store:
  git:
    storage: ".test/storage"
    path: ".test/storage"

packages:
  '**':
    access: $all
    publish: $all

logs:
  - { type: stdout, format: pretty, level: debug }

max_body_size: 1000mb
