name: Lock File Changes
on: [pull_request]
jobs:
  lock_file_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # yarn.lock
      - name: Yarn Lock Changes
        uses: Simek/yarn-lock-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          collapsibleThreshold: 1

      # composer.lock
      - name: Generate composer diff
        id: composer_diff
        uses: IonBazan/composer-diff-action@master
        with:
          base: ${{ github.event.pull_request.base.sha }}:apps/silverback-drupal/composer.lock
          target: apps/silverback-drupal/composer.lock
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.composer_diff.outputs.composer_diff }}
        with:
          header: composer-diff
          # Make the message look similar to the one produced by
          # Simek/yarn-lock-changes.
          message: |
            ## `composer.lock` changes
            
            <details>
            <summary>Click to toggle table visibility</summary>

            ${{ steps.composer_diff.outputs.composer_diff }}

            </details>
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.composer_diff.outputs.composer_diff == 0 }}
        with:
          header: composer-diff
          delete: true
