name: Recipes
on:
  workflow_dispatch:
  schedule:
    - cron: 0 2 * * 0
jobs:
  recipes:
    name: Test
    runs-on: ubuntu-latest
    env:
      LOG: silly
    steps:
      - name: Git mail
        run: git config --global user.email "kitt@amazee.com"

      - name: Git username
        run: git config --global user.name "K.I.T.T."

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # We can upgrade to PHP 8 when
          # - https://github.com/mglaman/phpstan-drupal supports it
          php-version: '7.4'

      - name: Read .nvmrc
        run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc| grep -oE '[0-9]+(\.[0-9]+)?(\.[0-9]+)?' | head -1)"
        id: node_version

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.node_version.outputs.NODE_VERSION }}"

      - name: Tell yarn to use bash
        run: >
          yarn config set script-shell /bin/bash

      - name: Install recipes
        run: npm install -g @amazeelabs/recipes

      - name: Create a monorepo
        run: >
          echo "test" | amazee-recipes create-monorepo &&
          git add README.md &&
          git commit -m "chore: executed 'create-monorepo' recipe"

      - name: Add a Gatsby website application
        working-directory: ./test
        run: >
          amazee-recipes add-gatsby
          git add README.md
          git commit -m "chore: executed 'add-gatsby' recipe"

      - name: Add a Drupal CMS application
        working-directory: ./test
        run: >
          amazee-recipes add-drupal
          git add README.md
          git commit -m "chore: executed 'add-drupal' recipe"

      - name: Add a Storybook UI packages
        working-directory: ./test
        run: >
          amazee-recipes add-storybook
          git add README.md
          git commit -m "chore: executed 'add-storybook' recipe"
