name: Release
on:
  push:
    branches:
      - development
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSL_PRIVATE }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Commons
        uses: ./.github/actions/commons

      - name: Configure NPM token
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> ~/.npmrc

      - name: Add auth token for 127.0.0.1
        run: echo "//127.0.0.1:4873/:_authToken=foo" >> ~/.npmrc

      - name: Debug npmrc
        run: cat ~/.npmrc

      - name: Npm version
        run: npm -v

      - name: Install dependencies
        run: pnpm i

      - name: Build packages
        run: pnpm build

      - name: Run static tests
        run: pnpm test:static

      - name: Run unit tests
        run: pnpm test:unit

      - name: Run integration tests
        run: pnpm test:integration

      - name: Start verdaccio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm git-registry:with-logs &

      - name: Wait a moment
        run: sleep 5

      - name: Check for git diff
        run: git diff --exit-code

      - name: Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: pnpm lerna run deploy --since

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm lerna publish -y

      - name: Verdaccio log
        run: cat /tmp/verdaccio.log || true
        if: always()
      - name: Gatsby log
        run: cat /tmp/gatsby.log || true
        if: always()
      - name: Drupal log
        run: cat /tmp/drupal.log || true
        if: always()
