name: Release
on:
  push:
    branches:
      - development
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Git mail
        run: git config --global user.email "kitt@amazee.com"

      - name: Git username
        run: git config --global user.name "K.I.T.T."

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # wikimedia/composer-merge-plugin does not support Composer 2.0 yet
      # https://github.com/wikimedia/composer-merge-plugin/issues/184
      - name: Use Composer 1
        run: sudo composer selfupdate --1

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSL_PRIVATE }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: |
            node_modules
            **/vendor
          key: npm-${{ hashFiles('**/package.json', '**/composer.json') }}

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> .npmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Bootstrap Lerna
        run: yarn lerna bootstrap

      - name: Add drupal.org ssh key
        run: ssh-keyscan git.drupal.org >> ~/.ssh/known_hosts

      - name: Run tests
        run: yarn test

      - name: Build packages before releasing them
        run: yarn lerna run prepublishOnly && yarn lerna run prepare
        working-directory: packages/npm/verdaccio-git

      - name: Start verdaccio
        run: yarn git-registry &

      - name: Wait a moment
        run: sleep 5

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn lerna publish -y
