name: Release
on:
  push:
    branches:
      - development
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSL_PRIVATE }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commons
        uses: ./.github/actions/commons

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> .npmrc

      - name: Add auth token for 127.0.0.1
        run: echo "//127.0.0.1:4873/:_authToken=foo" >> .npmrc

      - name: Add auth token for localhost
        run: echo "//localhost:4873/:_authToken=foo" >> .npmrc

      - name: Debug npmrc
        run: cat .npmrc

      - name: Npm version
        run: npm -v

      - name: Install dependencies
        run: pnpm i

      - name: Build packages
        run: pnpm build

      - name: Add drupal.org ssh key
        run: ssh-keyscan git.drupal.org >> ~/.ssh/known_hosts

      - name: Run static tests
        run: pnpm test:static

      - name: Run unit tests
        run: pnpm test:unit

      - name: Run integration tests
        run: pnpm test:integration

      - name: Start verdaccio
        run: pnpm git-registry &

      - name: Wait a moment
        run: sleep 5

      - name: Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: pnpm lerna run deploy --since

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm lerna publish -y
