name: Test Recipes with NPM
on:
  workflow_dispatch:
jobs:
  test:
    name: Test Recipes with NPM
    runs-on: ubuntu-20.04
    steps:

      - name: Git mail
        run: git config --global user.email "kitt@amazee.com"
      - name: Git username
        run: git config --global user.name "K.I.T.T."

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2
          bundler-cache: true

      - name: Install Pygmy
        run: gem install pygmy

      - name: Start Pygmy
        run: pygmy up

      - name: Read .nvmrc
        run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc| grep -oE '[0-9]+(\.[0-9]+)?(\.[0-9]+)?' | head -1)"
        id: node_version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.node_version.outputs.NODE_VERSION }}"

      - name: Tell yarn to use bash
        run: yarn config set script-shell /bin/bash

      - name: Run recipe tests
        run: cd packages/npm/@amazeelabs/recipes && ./test-npm.sh
