name: Test
on:
  pull_request:
    branches:
      - development
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Git mail
        run: git config --global user.email "kitt@amazee.com"

      - name: Git username
        run: git config --global user.name "K.I.T.T."

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # wikimedia/composer-merge-plugin does not support Composer 2.0 yet
      # https://github.com/wikimedia/composer-merge-plugin/issues/184
      - name: Use Composer 1
        run: composer selfupdate --1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: |
            node_modules
            **/vendor
          key: npm--${{ hashFiles('**/package.json', '**/composer.json') }}

      - name: Install dependencies
        run: yarn install

      - name: Bootstrap Lerna
        run: yarn lerna bootstrap

      - name: Run tests
        run: yarn test
