session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: en
    de: de
    fr: fr
    it: it
    '': null
  domains:
    en: ''
    de: ''
    fr: ''
    it: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
